services:
  melodarr-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/source
    environment:
      # Ensure files created inside the container align with your macOS host user
      - PUID=1000
      - PGID=1000
      - ASPNETCORE_ENVIRONMENT=Development
    # Keep container running transparently in the background
    tty: true
    init: true